Token = "bot token here"
AppID = 123
# directories to get images from
ImageDirs = ["/path/to/cats", "/path/to/more/cats"]
# in Content, "%filename%" gets replaced with the filename
Content = "take a look! %filename%"
# bot's "playing" status
ActivityName = "with a ball of yarn"
# name and description for slash command
CommandName = "cat"
CommandDescription = "send a random cat"

# periodically send images into these channels (channel ids)
PostChannels = [123, 123]
# how often to post images
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
PostInterval = "30m"
